### PR TITLE
Add survey

### PR DESCRIPTION
**Pull request by colbyhemond**
As of now a Survey component has been created. And the draft survey questions proposed have been implemented as a placeholder until the survey is finalized. I think some thought needs to go into how we want to store the survey results in the database. As of now I have an array of objects with the following properties:

- id: Int - a unique identifier in case it's needed
- question: String - contains the survey question
- answerName: String - used for html attribute `name`
- answerType: String - was used why trying to dynamically create each question with a child component (is obsolete for now in order to get the product shipped)
- answerOptions: Array - if radio or checkboxes, contains the different options
- answer: String - contains the answer
- other: String - used when there is a question with input type radio or checkbox and there is an other option.

Example:
```
id: 1,
question: "How satisfied are you with the speed of your internet service?",
answerName: "service-speed",
answerType: "radio",
answerOptions: [1,2,3,4,5],
answer: null,
other: ''
```

Side notes: There is some DB persistence work done, but I don't think it's stable yet. There is also a new survey page in order to test the survey, however I think we could use the survey component to render it after a speed test completes in the `speed.svelte` page possibly as a modal popup.

### CODE REVIEW

**Comment by colbyhemond** [comment]
Updated the survey with the new questions in the Notion doc. I need to go through and smooth out the styling before it's finalized. Then I'll work on connecting to the database.

**Comment by colbyhemond** [comment]
Working on connecting it to the database. Just need to finalize the Schema. Working on figuring out the best way to store the survey submissions.

**Comment by colbyhemond** [comment]
The survey is complete and persists to the database. This can be viewed and tested by going to the /survey endpoint. The page will need to be refactored to not show the survey results after submission, but is there for now to show and test until survey schema is refined or other solution is decided.

**Comment by colbyhemond** [comment]
The Survey database schema is currently:
```
const SurveySubmissionsSchema = new Schema({
  date: {
    type: String,
    default: Date.now(),
  },
  city: String,
  state: String,
  answers: [{
    questionId: String,
    answer: String
  }]
});
```

However I have the following concerns/questions:

- Currently the speed test saves city and state in the same field (at least that is how it is stores in `localStorage`, should we split those out, like how I have them in the Survey schema so that analytics can be performed at a granular basis more easily?
- Are there any demographic questions that need to be added to the survey? (for example, City and State, in the case that there is not speed test stored in `localStorage` to get that information from?
- One outstanding item I need to implement is allowing text submission for "Other" cases in checkbox answers, however this should not affect the Schema as this "Other" answer should be able to be pushed onto the array of answers

**Comment by ejolly** [comment]
@colbyhemond 

- Yup I think it makes sense to store city and state separately
- I don't think we'll be collecting any more demographics, but I think we want to add one field to the last survey question where users can optionally add their email address for future contact
- Sounds good

Thanks for the work on all this! If you have sometime do you want to touch base before merging this in? The reason I ask is because there was some consensus at tonight's work night that it would be nice to streamline the survey into the speed test page. So a user would do a speed test and the optionally do the survey, rather than having the survey be an entirely separate thing. That way a user can do the speedtest, speedtest + survey, or neither rather than giving them an option to complete the survey without doing a speedtest. Ideally we should be storing the speedtest record alongside the survey responses so we can optionally visualizes the survey responses on a map as well.

Happy to talk through this!

**Comment by colbyhemond** [comment]
Absolutely! I created the speediest as a component so we can eventually do that. I agree let's touch base and we can make the process as streamlined as possible!

**Pull request merged**
